### ISSUE TITLE
Collect together the various collected use case documents and produce USECASES.md

### ISSUE THREAD

**Issue by kemp-google** [ga4gh-discovery/data-connect#1]
I'd like to collect up the various documents we have documenting use cases.

The ones I'm aware of (I need to track down links still):
* The document containing queries people want to run
* The formal use case collection document
* The spreadsheet with various feature bits

**Comment by kemp-google** [comment]
Marc provides some links on the chat in the call (some of these are ACL'd to a smaller group)
https://docs.google.com/document/d/1IseLxLSlhN2-PI0_ZFkieClSa3q70MJGZS5XxO-meCQ/edit
https://drive.google.com/drive/u/0/folders/1HsHF0p1JslKTZBJsItnTn2fs0bH9WM3t
https://docs.google.com/document/d/1YKGxY8NNWeN8a8WIgqrvukFRlwnQzEW6NRyHTMM02aY/edit

**Comment by mcupak** [comment]
Closed by #8.
