### ISSUE TITLE
Clarify and/or rename DatasetInfo location field

### ISSUE THREAD

**Issue by jvlasblom** [ga4gh-discovery/data-connect#11]
The 'location' field in DatasetInfo seems redundant.  If I have the id of a dataset, I can fetch that dataset via GET /dataset/{id}.  It's unclear when the location field should be preferred, and also whether the intent of the location field is just descriptive (e.g. to record the original location or "source of truth").

**Comment by mcupak** [comment]
This looks resolved, please reopen if needed.
