### ISSUE TITLE
Endpoint naming consistency

### ISSUE THREAD

**Issue by davidlougheed** [ga4gh-discovery/data-connect#18]
Why does the API have the endpoint `/dataset/<id>` with a singular "dataset" and `/datasets` as plural? To my knowledge this is uncommon within GA4GH APIs (such as service registry, which uses `/services` and `/services/<id>`, or the WES API)

**Comment by jfuerth** [comment]
Hi David,

This was a deliberate choice to allow very low cost implementations of this API by uploading a set of JSON files to any web server (in particular, a cloud bucket such as Amazon S3 or Google GCS).

There is an explanation with a link to an example here: https://github.com/ga4gh-discovery/ga4gh-discovery-search#dataset-in-a-bucket-no-code-implementation

**Comment by davidlougheed** [comment]
Alright, that makes sense, thank you!
In the readme link it mentions "`dataset/{id}`: served in response to `GET /datasets/{id}`"; should the second URI be `/dataset/{id}` then?

**Comment by jfuerth** [comment]
Yes, thank you! The original design didn't permit the "dataset-in-a-bucket" scenario, and I guess we missed changing that in the README when we did the update. I'll make a PR to fix that error.
